# Generated by Django 5.0.4 on 2024-04-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('scrap_type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
